// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkPCfvQYYs9ECn5DAye7J8vGZHdMmI10I',
    appId: '1:32797416571:web:0e75988f80b608e2e2d6de',
    messagingSenderId: '32797416571',
    projectId: 'interufmt-7861a',
    authDomain: 'interufmt-7861a.firebaseapp.com',
    storageBucket: 'interufmt-7861a.firebasestorage.app',
    measurementId: 'G-KZLVY2KM9S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwL_l14pLp7n0Ya9i1-HX7Vy9kKzRNLCw',
    appId: '1:32797416571:android:38f6371ae1aa7791e2d6de',
    messagingSenderId: '32797416571',
    projectId: 'interufmt-7861a',
    storageBucket: 'interufmt-7861a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCa_myXJBDp2DtD_rjf2DYpihCZitNq44c',
    appId: '1:32797416571:ios:2ac8acebc2c5bfe5e2d6de',
    messagingSenderId: '32797416571',
    projectId: 'interufmt-7861a',
    storageBucket: 'interufmt-7861a.firebasestorage.app',
    iosBundleId: 'io.interufmt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCa_myXJBDp2DtD_rjf2DYpihCZitNq44c',
    appId: '1:32797416571:ios:6f6a611954dc3da0e2d6de',
    messagingSenderId: '32797416571',
    projectId: 'interufmt-7861a',
    storageBucket: 'interufmt-7861a.firebasestorage.app',
    iosBundleId: 'com.example.interufmt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkPCfvQYYs9ECn5DAye7J8vGZHdMmI10I',
    appId: '1:32797416571:web:9e09506f3c3442d7e2d6de',
    messagingSenderId: '32797416571',
    projectId: 'interufmt-7861a',
    authDomain: 'interufmt-7861a.firebaseapp.com',
    storageBucket: 'interufmt-7861a.firebasestorage.app',
    measurementId: 'G-YT3375Z7KC',
  );

}